server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/vue_test_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul 
    username: vue_test
    password: 1234
  jpa:
    #database: mysql
    hibernate:
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # default
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update   # 프로젝트 실행시 자동으로 DDL(create, alter, drop) 을 생성할 것 인지 결정하는 설정 # create : 매번 테이블 생성을 새로 시도한다 / update : 변경이 필요한 경우 alter로 변경되고 테이블이 없는경우 create가 된다
    properties:
      hibernate:
        show_sql: false   # 콘솔에 표시
        format_sql: true  # 쿼리 들여쓰기 등 포맷에 맞춰 표출
        use_sql_comments: true # 주석 표시
    database-platform: org.hibernate.dialect.MariaDBDialect # MariaDB 상세 지정